version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./book-service/src:/usr/src/app/book-service/src
      - ./notifier-service/src:/usr/src/app/notifier-service/src
    ports:
      - "3000:3000" # Port for book service
      - "4000:4000" # Port for notifier service
    environment:
      - NODE_ENV=development
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DATABASE}
    ports:
      - "5432:5432"
    env_file:
      - .env
